# Generated by Django 5.2.12 on 2026-04-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='product_code',
            field=models.CharField(blank=True, default='EPAYTEST', max_length=100, null=True),
        ),
    ]
